### PR TITLE
fix(l10n): ensure the correct language is selected in localizeTimestamp

### LINKED ISSUE #33: Moment is not using Arabic translations in last sync text
I have my browser languages set to “Arabic→English”. Technically it’s "ar:en".

Opening Firefox Accounts and checking the “Devices & Apps” section, you can see that `fromnow` is not using the Arabic translations. I can’t be sure if this is a server issue or an implementation issue. Checking Moment's code, Arabic translations [are available](https://github.com/moment/moment/blob/develop/locale/ar.js).

This is the production server. I couldn’t check the testing one as I don’t intend to connect anything with testing stuff :)
Screenshot:
screenshot_2018-08-24 1

EDIT: Sorry, I wasn’t sure if I should report about this here or to fxa-content-server.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #33.

The test of `supportedLanguages.indexOf` was mistakenly checking against `0` instead of `-1`. This meant that the first item in our list of supported languages, arabic, was never being matched and other, unsupported ones were being matched.

Furthermore, the `accept-languages` package assumes it is initialised with an array of languages that are sorted in order of precedence. This meant our `defaultLanguage` option was effectively being ignored because it was not at the start of the list.

This change fixes both issues and tweaks the tests so that they will fail if either one regresses in the future.

@mozilla/fxa-devs r?

### CODE REVIEW

File: test/l10n/localizeTimestamp.js [hunk 1]
```diff
@@ -57,12 +57,20 @@ describe('l10n/localizeTimestamp:', () => {
       assert.equal(format(Date.now() - 1, 'es-mx, ru'), 'hace unos segundos');
     });
 
+    it('returns a fallback language if called with unsupported language variations', () => {
+      assert.equal(format(Date.now() - 1, 'de, fr;q=0.8, ru;q=0.5'), 'несколько секунд назад');
```
Comment (shane-tomlinson) [inline test/l10n/localizeTimestamp.js]: In this test are both Danish and French unsupported?

Comment (philbooth) [reply test/l10n/localizeTimestamp.js]: Yep. (well except it's German not Danish, but yep)
